### ISSUE TITLE
run https://github.com/kubeflow/pytorch-operator/blob/master/sdk/python/test/test_e2e.py failed

### ISSUE THREAD

**Issue by seansxl** [kubeflow/pytorch-operator#363]
Traceback (most recent call last):
  File "/home/sxl/PythonDev/k8s_client/pytorch_main.py", line 69, in <module>
    pytorchjob_client.create(pytorchjob)
  File "/home/sxl/.local/lib/python3.8/site-packages/kubeflow/pytorchjob/api/py_torch_job_client.py", line 65, in create
    outputs = self.custom_api.create_namespaced_custom_object(
  File "/home/sxl/.local/lib/python3.8/site-packages/kubernetes/client/api/custom_objects_api.py", line 225, in create_namespaced_custom_object
    return self.create_namespaced_custom_object_with_http_info(group, version, namespace, plural, body, **kwargs)  # noqa: E501
  File "/home/sxl/.local/lib/python3.8/site-packages/kubernetes/client/api/custom_objects_api.py", line 344, in create_namespaced_custom_object_with_http_info
    return self.api_client.call_api(
  File "/home/sxl/.local/lib/python3.8/site-packages/kubernetes/client/api_client.py", line 348, in call_api
    return self.__call_api(resource_path, method,
  File "/home/sxl/.local/lib/python3.8/site-packages/kubernetes/client/api_client.py", line 170, in __call_api
    body = self.sanitize_for_serialization(body)
  File "/home/sxl/.local/lib/python3.8/site-packages/kubernetes/client/api_client.py", line 238, in sanitize_for_serialization
    for attr, _ in six.iteritems(obj.openapi_types)
AttributeError: 'V1PyTorchJob' object has no attribute 'openapi_types'

**Comment by gaocegege** [comment]
This repository will be deprecated soon, please open an issue at github.com/kubeflow/training-operator
